### ISSUE TITLE
Deathwatch: Various issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#557]
**File:** Deathwatch.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 
1. In Deathwatch veterans, the increased cost of combiweapons and storm bolters is not added in. 
2. The default power sword does not have it's cost added, but if you remove it and add the power sword from the replacement list it does. 
3. When adding a vanguard veteran or sergeant it will flag them not taking a jump pack as an error, when it should be a valid option.

**Comment by Mad-Spy** [comment]
1. DW don't pay the SIA tax; only models which were originally ADEPTUS ASTARTES Faction.
2. Will fix.
3. Unable to replicate. Vanguard Veterans give no errors when adding a Jump Pack. If you're trying to add a Jump Pack to a _Company Veteran_ you _will_ get an error, because only Wolves models can take one.
