### ISSUE TITLE
Grey knights shouldn't have melee weapons in the Equipment list

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-killteam#728]
**Describe the bug**
Basically the title. Grey knights gunner has proper melee weapons in the data file and it should only have bare fists

**Comment by Mad-Spy** [comment]
Grey Knight Gunners have never had melee weapons in the KT2021 data. I think you may have accidentally loaded the 2018 data instead. They were allowed melee weapons in the old rules.

**Comment by mcdehaan** [comment]
You're blazing fast 😄 
But the melee weapon is there in the 2021 edition:
I
<img width="482" alt="Schermafbeelding 2022-02-11 om 17 19 24" src="https://user-images.githubusercontent.com/31688921/153628495-32e8ea46-4645-48dd-b9dd-8a3ed76b9391.png">

**Comment by Mad-Spy** [comment]
The actual issue is not what you've fixed. Model choices are on the model, not in the Equipment list. That link in the Equipment list should be going to the "Melee Weapons Rare Equipment" group, but I accidentally pointed it to the melee weapons group instead.

Unfortunately, you fixed the symptom and not the disease. :)
