### ISSUE TITLE
[Anon] Bug report: 2021 - Inquisitorial Agents.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#873]
**File:** 2021 - Inquisitorial Agents.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** When selecting Sisters of Silence as an auxiliary force, selecting 5 Witchseeker gets "Inquisitorial Agents v15 (Inquisitorial Agents Kill Team) has 4 too many selections of Flamer (max 1)". I am yet to see anything suggesting it is not legal, and this seems to be unique issue to Witchseekers since 5 vigilators or prosecutors works fine

**Comment by mal20k** [comment]
Tested the latest version of Inquisitorial Agents (v16) in both NewRecruit and BattleScribe. This issue is only present in BattleScribe, which means it is likely an issue in Battlescribe itself. We no longer recommend usage of BattleScribe as it is abandonware and instead recommend using NewRecruit. Our data is not guaranteed to work with BattleScribe.
